# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaz_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, ventana1):
        ventana1.setObjectName("ventana1")
        ventana1.resize(772, 539)
        ventana1.setMinimumSize(QtCore.QSize(200, 200))
        self.centralwidget = QtWidgets.QWidget(ventana1)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 901, 511))
        self.label.setMinimumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("diseños/imagen_del_1.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.torneo_button = QtWidgets.QPushButton(self.centralwidget)
        self.torneo_button.setGeometry(QtCore.QRect(90, 350, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.torneo_button.setFont(font)
        self.torneo_button.setStyleSheet("QPushButton {\n"
"    background-color: #28a745;  /* Color de fondo verde */\n"
"    color: white;               /* Color del texto */\n"
"    border-radius: 5px;         /* Bordes redondeados */\n"
"    padding: 5px;               /* Espacio interno */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #218838;  /* Color cuando el mouse pasa encima */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1e7e34;  /* Color cuando el botón es presionado */\n"
"}\n"
"")
        self.torneo_button.setObjectName("torneo_button")
        ventana1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ventana1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 772, 20))
        self.menubar.setObjectName("menubar")
        ventana1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ventana1)
        self.statusbar.setObjectName("statusbar")
        ventana1.setStatusBar(self.statusbar)

        self.retranslateUi(ventana1)
        self.torneo_button.clicked['bool'].connect(ventana1.abrir) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ventana1)

    def retranslateUi(self, ventana1):
        _translate = QtCore.QCoreApplication.translate
        ventana1.setWindowTitle(_translate("ventana1", "Ventana1"))
        self.torneo_button.setText(_translate("ventana1", "NUEVO TORNEO"))
